# -*- coding: utf-8 -*-
"""product review summarize

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1epuu-X7ycBGs7nZu66u-m-nxfL3gES_O
"""

!pip install transformers torch pandas

from transformers import pipeline
import pandas as pd
# Load sentiment analysis model
sentiment = pipeline("sentiment-analysis")
# Sample product review(you can change only this text later)
reviews = """the laptop starts quickly and works smoothly for deily tasks.
the screen quqlity is clear and good for watching videos.
battery backup is average and needs charging often.
the fan makes noise when many apps are running.
overall , it is good laptop for students but not for gaming.
"""
# Split review into sentences
sentences = reviews.split(".")
pros = []
cons = []

for s in sentences:
    s = s.strip()
    if s == "":
       continue

    result = sentiment(s)[0]
    if result["label"] == "POSITIVE":
       pros.append(s)
    elif  result["label"] == "NEGATIVE":
       cons.append(s)
# Take only 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]
# Create table
df = pd.DataFrame({
     "pros":pros,
     "cons":cons
})
df