# -*- coding: utf-8 -*-
"""text generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XpxZhq6_taD8MKhDbhYq7E1277oekkWB
"""

!pip install transformers torch





from transformers import pipeline
# load text generation model(Gen AI)
generator = pipeline(
    "text-generation",
    model="gpt2"
)
# input prompt
prompt="Artifical Intelligence in finance will"
# Generate text
result=generator(prompt,max_length=50,num_return_sequences=1)
print("Ai Generated text:")
print(result[0]['generated_text'])