# -*- coding: utf-8 -*-
"""timetable

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16-Whn9ACBI6-T8B92aMRdcPoXkcfWn8W
"""

import pandas as pd
import random

print("TIMETABLE GENERATOR\n")

#user Inputs
subjects_input =input("Enter subjects (comma separated): ")
days_input = input("Enter days (comma separated): ")
periods_per_day = int(input("Enter number of periods per day: "))

#process Inputs
subjects = [s.strip() for s in subjects_input.split(",") if s.strip()]
days = [d.strip() for d in days_input.split(",") if d.strip()]

#validation
if len(subjects) == 0 or len(days) == 0 or periods_per_day <= 0:
    print("Invalid input. please try again.")
else:
   timetable = {}

   for days in days:
      timetable[day] = random.choices(subjects, k=periods_per_day)

   #create Dataframe
   df = pd.Dataframe(timetable)
   df.index = [f"period {i+1}"  for  i in range(periods_per_day)]

   print("\nTimetable Generated successfully\n")
   display(df)

   #save timetable
   df.to_csv("timetable.csv")
   print("\nTimetable saved as timetable.csv")